import {
  Check,
  Copy,
  Download,
  KeyRound,
  Puzzle,
  Sparkles,
  X,
} from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import { api } from "../lib/api";
import { useAuth } from "../lib/AuthContext";

/**
 * Welcome / extension-install tour. Auto-opens once per user (gated on
 * `users.onboarding_dismissed_at`) and is also reachable from the
 * Settings modal as a "show again" entry. Three steps:
 *
 *   1. Mint a long-lived token (calls /api/auth/extension-token).
 *   2. Download the packaged extension zip from /downloads/.
 *   3. Paste API URL + token into the extension's settings pane.
 *
 * Dismiss commits the timestamp server-side so the modal stays
 * silent across devices.
 */

const TOKEN_REVEAL_ANIM_MS = 200;

interface VersionResponse {
  version: string;
}

interface Props {
  open: boolean;
  onClose: () => void;
}

export default function OnboardingModal({ open, onClose }: Props) {
  const { t } = useTranslation();
  const { refreshUser } = useAuth();
  const [token, setToken] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [version, setVersion] = useState<string | null>(null);
  const [dontShowAgain, setDontShowAgain] = useState(true);

  // Read the bundled extension version once when the modal opens.
  // Generated by scripts/build-extension-zip.sh — falls back silently
  // if the file is missing (e.g. dev server without prior build).
  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    fetch("/downloads/extension-version.json", { cache: "no-store" })
      .then((r) => (r.ok ? (r.json() as Promise<VersionResponse>) : null))
      .then((v) => {
        if (!cancelled && v?.version) setVersion(v.version);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [open]);

  // ESC to close. Mirrors the SettingsModal pattern.
  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  async function handleGenerateToken() {
    setGenerating(true);
    try {
      const { access_token } = await api.createExtensionToken();
      setToken(access_token);
    } catch {
      // Surfaces via the disabled-state hint; no toast yet because the
      // root cause is almost always a network blip.
    } finally {
      setGenerating(false);
    }
  }

  async function handleCopy() {
    if (!token) return;
    try {
      await navigator.clipboard.writeText(token);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard refused — user can still select + copy manually */
    }
  }

  async function handleClose() {
    if (dontShowAgain) {
      try {
        await api.dismissOnboarding();
        await refreshUser();
      } catch {
        /* dismissal is a soft preference — closing wins either way */
      }
    }
    onClose();
  }

  if (!open) return null;

  const apiBaseUrl =
    (import.meta.env.VITE_API_BASE_URL as string | undefined) ||
    window.location.origin;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center sm:p-4"
      role="dialog"
      aria-modal="true"
      aria-label={t("onboarding.title", { defaultValue: "Welcome to Mindshift" })}
    >
      <button
        type="button"
        onClick={handleClose}
        className="absolute inset-0 bg-ink-900/40 backdrop-blur-md modal-backdrop-enter"
        aria-label="Close onboarding"
      />

      <div className="relative flex h-[100vh] w-[100vw] max-h-none max-w-none flex-col overflow-hidden border-0 bg-ink-800 surface-elevated modal-card-enter sm:h-auto sm:max-h-[90vh] sm:w-[640px] sm:max-w-[92vw] sm:rounded-2xl sm:border sm:border-ink-700">
        {/* Header */}
        <div className="flex flex-shrink-0 items-start justify-between gap-3 border-b border-ink-700 bg-gradient-to-br from-ink-800 to-ink-900/60 px-5 py-4 sm:px-6">
          <div className="flex min-w-0 items-start gap-3">
            <span className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-lg bg-amber-500/15 ring-1 ring-amber-500/30">
              <Sparkles className="h-4 w-4 text-amber-300" />
            </span>
            <div className="min-w-0">
              <h2 className="text-base font-semibold text-ink-100">
                {t("onboarding.title", { defaultValue: "Welcome to Mindshift" })}
              </h2>
              <p className="mt-0.5 text-xs text-ink-400">
                {t("onboarding.subtitle", {
                  defaultValue:
                    "Set up the browser extension in three quick steps.",
                })}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={handleClose}
            aria-label="Close"
            className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-md text-ink-400 transition hover:bg-ink-700 hover:text-ink-100"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Scrollable body — three step cards */}
        <div className="flex-1 overflow-y-auto px-5 py-5 sm:px-6">
          {/* Step 1 — token */}
          <Step
            n={1}
            icon={KeyRound}
            title={t("onboarding.step1.title", { defaultValue: "Generate your access token" })}
            body={t("onboarding.step1.body", {
              defaultValue:
                "The extension needs a long-lived token to talk to your Mindshift backend. Click below to mint one.",
            })}
          >
            {token == null ? (
              <button
                type="button"
                onClick={handleGenerateToken}
                disabled={generating}
                className="inline-flex items-center gap-2 rounded-md bg-ink-100 px-3 py-1.5 text-xs font-medium text-ink-900 transition disabled:opacity-50 hover:bg-white"
              >
                {generating
                  ? t("onboarding.step1.generating", { defaultValue: "Generating…" })
                  : t("onboarding.step1.button", { defaultValue: "Generate token" })}
              </button>
            ) : (
              <div className="flex items-center gap-2">
                <code
                  className="flex-1 truncate rounded-md border border-ink-700 bg-ink-900/60 px-2.5 py-1.5 font-mono text-[11px] text-ink-200"
                  style={{ animation: `fadeIn ${TOKEN_REVEAL_ANIM_MS}ms ease` }}
                  title={token}
                >
                  {token}
                </code>
                <button
                  type="button"
                  onClick={handleCopy}
                  className="inline-flex items-center gap-1.5 rounded-md border border-ink-700 bg-ink-800 px-2.5 py-1.5 text-xs text-ink-200 transition hover:bg-ink-700"
                  aria-label="Copy token"
                >
                  {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
                  <span>
                    {copied
                      ? t("onboarding.step1.copied", { defaultValue: "Copied" })
                      : t("onboarding.step1.copy", { defaultValue: "Copy" })}
                  </span>
                </button>
              </div>
            )}
          </Step>

          {/* Step 2 — download */}
          <Step
            n={2}
            icon={Download}
            title={t("onboarding.step2.title", { defaultValue: "Download the browser extension" })}
            body={t("onboarding.step2.body", {
              defaultValue:
                "Unpack the ZIP, then load it as an unpacked extension at chrome://extensions (Developer mode → Load unpacked).",
            })}
          >
            <div className="flex flex-wrap items-center gap-3">
              <a
                href="/downloads/mindshift-extension.zip"
                download
                className="inline-flex items-center gap-2 rounded-md bg-ink-100 px-3 py-1.5 text-xs font-medium text-ink-900 transition hover:bg-white"
              >
                <Download className="h-3.5 w-3.5" />
                {t("onboarding.step2.button", { defaultValue: "Download .zip" })}
              </a>
              {version && (
                <span className="text-[11px] text-ink-500">
                  {t("onboarding.step2.version", { defaultValue: "Version" })} {version}
                </span>
              )}
            </div>
          </Step>

          {/* Step 3 — paste into extension */}
          <Step
            n={3}
            icon={Puzzle}
            title={t("onboarding.step3.title", { defaultValue: "Connect the extension" })}
            body={t("onboarding.step3.body", {
              defaultValue:
                "Open the extension's side panel → Settings (gear icon). Paste these two values, then click Save.",
            })}
            last
          >
            <dl className="mt-1 space-y-2 rounded-md border border-ink-700 bg-ink-900/40 p-3 text-xs">
              <div className="flex flex-col gap-0.5">
                <dt className="text-[10px] uppercase tracking-wider text-ink-500">
                  {t("onboarding.step3.apiUrlLabel", { defaultValue: "API URL" })}
                </dt>
                <dd className="font-mono text-ink-200">{apiBaseUrl}</dd>
              </div>
              <div className="flex flex-col gap-0.5">
                <dt className="text-[10px] uppercase tracking-wider text-ink-500">
                  {t("onboarding.step3.tokenLabel", { defaultValue: "Token" })}
                </dt>
                <dd className="font-mono text-ink-200">
                  {token ?? t("onboarding.step3.tokenPlaceholder", { defaultValue: "(generate in step 1)" })}
                </dd>
              </div>
            </dl>
          </Step>
        </div>

        {/* Footer — don't-show-again + close */}
        <div className="flex flex-shrink-0 items-center justify-between gap-3 border-t border-ink-700 bg-ink-900/40 px-5 py-3 sm:px-6">
          <label className="inline-flex items-center gap-2 text-xs text-ink-300">
            <input
              type="checkbox"
              checked={dontShowAgain}
              onChange={(e) => setDontShowAgain(e.target.checked)}
              className="h-3.5 w-3.5 rounded border-ink-600 bg-ink-900 text-amber-400 focus:ring-amber-500/40"
            />
            {t("onboarding.dontShowAgain", { defaultValue: "Don't show this again" })}
          </label>
          <button
            type="button"
            onClick={handleClose}
            className="rounded-md bg-ink-100 px-3 py-1.5 text-xs font-medium text-ink-900 transition hover:bg-white"
          >
            {t("onboarding.close", { defaultValue: "Got it" })}
          </button>
        </div>
      </div>
    </div>
  );
}

function Step({
  n,
  icon: Icon,
  title,
  body,
  children,
  last,
}: {
  n: number;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  body: string;
  children: React.ReactNode;
  last?: boolean;
}) {
  return (
    <div className={`flex gap-3 ${last ? "" : "pb-5"}`}>
      <div className="flex flex-col items-center">
        <span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-ink-700 text-xs font-semibold text-ink-200 ring-1 ring-ink-600">
          {n}
        </span>
        {!last && <span className="mt-1 w-px flex-1 bg-ink-700" aria-hidden="true" />}
      </div>
      <div className="min-w-0 flex-1 pb-1">
        <div className="flex items-center gap-2">
          <Icon className="h-4 w-4 text-ink-400" />
          <h3 className="text-sm font-medium text-ink-100">{title}</h3>
        </div>
        <p className="mt-1 text-xs leading-relaxed text-ink-400">{body}</p>
        <div className="mt-3">{children}</div>
      </div>
    </div>
  );
}
